spring: 
  datasource: 
    url: jdbc:h2:~/test
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa: 
    generate-ddl: true
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 
            client-secret: 